modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"
[[mods]] 
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
authors="Cake"
description='''
A minecraft mod library designed to extend the accessibility and capability of Create's systems. Primarily for use with mods developed by Aztech group.
'''
[[mixins]]
config="${mod_id}.mixins.json"
[[dependencies.${mod_id}]] 
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
